version: '3.8'

services:
  db:
    image: postgres:15
    container_name: meu-postgres
    environment:
      POSTGRES_DB: meudb
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  db_data:
